### ISSUE TITLE
Home Assistant Integration

### ISSUE THREAD

**Issue by ArchGalileu** [gnulabis/devimote#1]
Congratulations

So much searching for an way to communicate with Devialet Expert ;)

How to integrate with Home Assistant? Any idea?

Best regards
ArchGalileu

**Comment by gnulabis** [comment]
Apologies for the veeeery late reply and thank you for your kind words.
I've never used home assistant, I barely know the name, so I can't really help you there.

**Comment by gnulabis** [comment]
@ArchGalileu , you might want to have a look at #4.
