### ISSUE TITLE
Devimote should not require exclusive access to Devialet status packets

### ISSUE THREAD

**Issue by pisabell2** [gnulabis/devimote#3]
In my attempts to use Devimote for controlling my system made up of three chained D220 PRO, I stumbled onto an unexpected problem.

At this time I am using Roon for streaming digital files to my Devialet system. As it turns out, Roon appears to be monitoring the same UDP status packets as Devimote, and Devimote refuses to start whenever Roon is running, which in my case normally means all the time. As soon as I stop Roon, I can start Devimote allright.

I am a newbee at Python, but from what I have been able to gather, there used to be an option that would allow Python to share access to the relevant UDP packets, and that option seems to have been eliminated in recent versions of Python. 

Hopefully, expert users of Python will be able to suggest a way to obtain that shared access anyway. After all, sharing is fine between Roon and some other pieces of software, such as the Devialet Android app.

**Comment by gnulabis** [comment]
Hi, do you have link(s) to this discussion on the removal of shared UDP listening in recent Python?

**Comment by pisabell2** [comment]
> Hi, do you have link(s) to this discussion on the removal of shared UDP listening in recent Python?

I read something claiming that socket reuse was no longer allowed in recent versions of Python (I don't remember exactly where that was). But apparently, this is false. I just managed to get Roon and Devimote workconcurrently by adding one line to Devimote:

```
 def update(self):
        '''Try to get UDP status packet and decode it'''
        sock = socket.socket(socket.AF_INET,    # Internet
                             socket.SOCK_DGRAM) # UDP
        sock.setsockopt(socket.SOL_SOCKET, socket.SO_REUSEADDR, 1)  # added line
        sock.bind(('', self.UDP_PORT_STATUS))
        sock.settimeout(2)
```

Consequently, I am closing this thread. Apologies for my error.

**Comment by gnulabis** [comment]
No wait, I reopen this until I've merged your change to the main code.

**Comment by gnulabis** [comment]
Ok, so here's the fix:

https://github.com/gnulabis/devimote/commit/f03b2ed00c56eaa01318436ed632146c287169b7

I'll test it this afternoon and if it works I'll merge it to the main branch.

**Comment by pisabell2** [comment]
Ok, great!

**Comment by gnulabis** [comment]
Ok, it works, I'm merging it.
